services:
  - type: web
    name: task-manager
    env: ruby
    buildCommand: bundle install && yarn install && bundle exec rake assets:precompile
    startCommand: bundle exec rails server
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: task-manager-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
databases:
  - name: task-manager-db
