default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: task_manager_development
  username: <%= ENV["TASK_MANAGER_DEV_DATABASE_USERNAME"] %>
  password: <%= ENV["TASK_MANAGER_DEV_DATABASE_PASSWORD"] %>
  host: localhost
  port: 5432

test:
  <<: *default
  database: task_manager_test
  username: <%= ENV["TASK_MANAGER_DEV_DATABASE_USERNAME"] %>
  password: <%= ENV["TASK_MANAGER_DEV_DATABASE_PASSWORD"] %>
  host: localhost
  port: 5432

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
